#数据库
spring:
  datasource:
     url: jdbc:mysql://39.106.51.17:3306/test
     username: root
     password: root123
     driver-class-name: com.mysql.jdbc.Driver

#mybatis字段名驼峰转换
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
     
#自定义属性配置 
my:
  name: nxd
